### ISSUE TITLE
[@elastic/ecs-winston-format] Missing `triple-beam` dependency

### ISSUE THREAD

**Issue by rtritto** [elastic/ecs-logging-nodejs#108]
[loggers/winston/index.js](https://github.com/elastic/ecs-logging-nodejs/blob/master/loggers/winston/index.js) file use `triple-beam` dependency that's not included in `package.json` dependencies:
```js
...
const { MESSAGE } = require('triple-beam')
...
```

## Steps to reproduce
1. `yarn init -y`
2. `yarn set version berry`
3. `yarn add @elastic/ecs-winston-format winston`
4. Create `index.js` file
```js
const winston = require('winston')
const ecsFormat = require('@elastic/ecs-winston-format')

const logger = winston.createLogger({
  level: 'info',
  format: ecsFormat(),
  transports: [
    new winston.transports.Console()
  ]
})

logger.info('test1')
```
5. `yarn node index`

```console
C:\test-ecs-winston\.pnp.cjs:10188
    throw firstError;
    ^

Error: @elastic/ecs-winston-format tried to access triple-beam, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: triple-beam
Required by: @elastic/ecs-winston-format@npm:1.3.1 (via C:\test-ecs-winston\.yarn\cache\@elastic-ecs-winston-format-npm-1.3.1-8fc543f859-49a7767c64.zip\node_modules\@elastic\ecs-winston-format\)

Require stack:
- C:\test-ecs-winston\.yarn\cache\@elastic-ecs-winston-format-npm-1.3.1-8fc543f859-49a7767c64.zip\node_modules\@elastic\ecs-winston-format\index.js
- C:\test-ecs-winston\index.js
    at Function.external_module_.Module._resolveFilename (C:\test-ecs-winston\.pnp.cjs:10187:55)       
    at Function.external_module_.Module._load (C:\test-ecs-winston\.pnp.cjs:9986:48)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\test-ecs-winston\.yarn\cache\@elastic-ecs-winston-format-npm-1.3.1-8fc543f859-49a7767c64.zip\node_modules\@elastic\ecs-winston-format\index.js:20:21)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.external_module_.Module._load (C:\test-ecs-winston\.pnp.cjs:10036:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
```

## Workaround
Add in `.yarnrc.yml`:
```yml
packageExtensions:
  '@elastic/ecs-winston-format@*':
    dependencies:
      triple-beam: '*'
```
Run `yarn`.

**Comment by park78951** [comment]
resolved this?

**Comment by rtritto** [comment]
No, it's still not fixed.

PS: I added a workaraund in initial comment.

**Comment by trentm** [comment]
Sorry all about not being on this. You are correct, of course.
This package had been relying on **npm** flat/hoisted install behaviour where installing `winston` would install `triple-beam` in a place where `@elastic/ecs-winston-format` could get it.
